Testando #31

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,28 +1,12 @@
 #!/bin/sh
 
-CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD);
 
-COMMITS=$(git log $CURRENT_BRANCH --not --remotes --pretty=format:%s)
+COMMITS=$(git log $CURRENT_BRANCH --not --remotes --pretty=format:%s);
 
 for COMMIT in $COMMITS do
     PADRAO="$(echo $COMMIT | grep -o -E '#[0-9]*')";
     NUMERO_ISSUE="$(echo $PADRAO | grep -o -E '[0-9]+')";
-
-    # Verificando se está no padrão
-    if [ -z $PADRAO ];then
-        echo "Erro: Algum commit não está no padrão! Faltando #xxx. Ex.: #989 | 989 é uma issue";
-        echo "Push abortado."
-        exit 1
-    fi
-
-    # Verificando se foi atribuído um número de issue ao commit
-    if [ -z "$NUMERO_ISSUE" ];then
-        echo "Erro: Algum commit está com o número da issue faltando";
-        echo "Push abortado."
-        exit 1;
-    fi
-
-    echo "Verificando issue $PADRAO... [33%]";
 
     CURL_ARGS="-s -S -k";
     API_URL="https://api.github.com/repos/vitorhenriquec/TrabalhoGCM/issues/$NUMERO_ISSUE";
@@ -52,6 +36,8 @@ for COMMIT in $COMMITS do
     # Capturando a quantidade de labels associadas
     LENGTH="$(echo $JSON | jq '.labels | length')";
 
+    NAO_ENCONTROU_DOING = true;
+
     i=0
     while [ "$i" -lt "$LENGTH" ];do
         PARAMETRO=".labels[$i].name"
@@ -59,7 +45,14 @@ for COMMIT in $COMMITS do
         # Verificando se tem label "doing"
         if [ "$LABEL" = "\"doing\"" ];then
             # Achou label "doing"
+            $NAO_ENCONTROU_DOING = false
             break;
         fi
         i=$(( i + 1 ));
     done
+
+    if NAO_ENCONTROU_DOING;then
+        echo "Issue não possui a lable Doing. Push abortado."
+        exit 1;
+    fi
+done
